#!/usr/bin/env bash

set -e -o pipefail

# Name of the utility
readonly SELF=$(basename $0)
# Name of the service being controlled by the utility
readonly SERVICE_NAME="redis"
# Version of the utility
readonly VERSION="1.0.0"

# Shell output colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function that starts the service's container when possible
start() {

    # Check if container is already running
    if [ "$(container_status)" == "running" ]; then
        echored "$SERVICE_NAME is already running."
        exit 0;
    fi

    # Check if container image needs to be pulled
    if ! docker_image_exists; then
        echogreen "$SERVICE_NAME image not found.  Pulling image..."
        pull_latest_image
    fi

    echogreen 'Starting container...'
    if [ "$(container_status)" == "not found" ]; then
        docker_command
    else
        docker start $SERVICE_NAME 1> /dev/null
    fi

}

# Function that stops the service's container if it's running
stop() {

    # Check that container is running
    if [ "$(container_status)" != "running" ]; then
        echored "$SERVICE_NAME is not running."
        exit 0;
    fi

    # Stop the container
    echored "Stopping the $SERVICE_NAME container..."
    docker rm -f $SERVICE_NAME 1> /dev/null

}

# Function that first stops then starts the service's container
restart() {

    stop
    start

}

# Function that updates the container's image to the latest version
update() {

    echogreen "Pulling latest $SERVICE_NAME image..."
    pull_latest_image

}

########### Helper Functions ###########

# Returns the status of the container
container_status() {

    docker inspect --format='{{.State.Status}}' $SERVICE_NAME 2> /dev/null | sed '/^$/d' || echo 'not found'

}

# Function to handle exiting with an error
die() {

    echored >&2 "$@"
    exit 1

}

# Function that starts the service's container for the first time
docker_command() {

    docker run -d --restart=always -v /var/run/docker.sock:/tmp/docker.sock:ro -p 6379:6379 --name $SERVICE_NAME $SERVICE_NAME 1> /dev/null
}

# Returns true if docker is running, false otherwise
docker_is_running() {

    docker info &> /dev/null

}

# Returns true if container image exists, false otherwise
docker_image_exists() {

    [ "$(docker images $SERVICE_NAME | wc -l)" -eq "2" ]

}

# Function used to color echo text in green
echogreen() {

    echo -e "${GREEN}$@${NC}"

}

# Function used to color echo text in red
echored() {

    echo -e "${RED}$@${NC}"

}

pull_latest_image() {

    docker pull $SERVICE_NAME:latest

}

########### Script Utility Functions ###########

# Function that outputs usage information
usage() {

    cat <<EOF

Usage: $SELF [command]

  $SELF status      Prints the status of the $SERVICE_NAME container
  $SELF start       Starts the $SERVICE_NAME container
  $SELF stop        Stops the $SERVICE_NAME container
  $SELF restart     Restarts the $SERVICE_NAME container
  $SELF update      Pulls the latest image for the $SERVICE_NAME container
  $SELF help        Shows this message
  $SELF version     Prints the version number

EOF

}

# Function that outputs version information
version() {

    echo "$SELF version $VERSION"

}

# Function that outputs the status of the utility
status() {

    cat <<EOF

Docker:     running
Image:      $(docker_image_exists && echo 'downloaded')$(docker_image_exists || echo 'not found')
Container:  $(container_status)

EOF

}

case $1 in
    help|-h|--help)
        usage
        exit 0
    ;;

    version|--version)
        version
        exit 0
    ;;

    status|start|stop|restart|update)
        # Check that docker is running
        ! [ docker_is_running ] && die "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

        # Calls one of the methods
        $1
    ;;

    *)
        usage
        exit 0
    ;;
esac
